name: Display GitHub Actions secrets
on: [workflow_dispatch]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up secrets file
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
        STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
        CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
      run: |
        echo $ARM_CLIENT_ID >> secrets.txt
        echo $ARM_CLIENT_SECRET >> secrets.txt
        echo $ARM_TENANT_ID >> secrets.txt
        echo $ARM_SUBSCRIPTION_ID >> secrets.txt
        echo $RESOURCE_GROUP >> secrets.txt
        echo $STORAGE_ACCOUNT >> secrets.txt
        echo $CONTAINER_NAME >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2