# TODO: break workflow in 2 stages (jobs) - validate and plan

name: 'Terraform-PR'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  TF_LOG: INFO
  TF_IN_AUTOMATION: TRUE

jobs:
  terraform:
    name: 'Terraform-PR'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest or windows-latest. Set the working directory to main for the config files
    defaults:
      run:
        shell: bash
        working-directory: ./main

    steps:
      # Checkout the repository on the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Install the preferred version of Terraform CLI
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest
          # cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }} # Disabled: The API token for a Terraform Cloud/Enterprise instance to place within the credentials block of the Terraform CLI configuration file (optional)

      # Install Terragrunt
      - name: Install Terragrunt
        run: |
          sudo wget -q -O /bin/terragrunt "https://github.com/gruntwork-io/terragrunt/releases/download/v0.39.2/terragrunt_linux_amd64"
          sudo chmod +x /bin/terragrunt
          terragrunt -v

      # Run terraform fmt
      - name: Terraform Format
        id: tf_fmt
        # if: github.ref != 'refs/heads/main' # Disabled for the time being
        run: terraform fmt -check

      # Run terragrunt hclfmt
      - name: Terragrunt Format
        id: tg_hclfmt
        if: github.ref != 'refs/heads/main'
        run: terragrunt hclfmt

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        id: tf_init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
          STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
          CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
        run: terraform init -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME" -backend-config="resource_group_name=$RESOURCE_GROUP"

      # Run terraform validate
      - name: Terraform Validate
        id: tf_validate
        # if: github.ref != 'refs/heads/main' && (success() || failure()) # Disabled for the time being
        run: terraform validate -no-color

      # Run terragrunt validate
      - name: Terragrunt Validate
        id: tg_validate
        if: github.ref != 'refs/heads/main' && (success() || failure())
        run: terragrunt run-all validate

      # Verify Terraform module files with Checkov
      - name: Checkov GitHub Action
        id: checkov_verify_files
        uses: bridgecrewio/checkov-action@master
        continue-on-error: true
        with:
          directory: .
          # file: example/tfplan.json # optional: provide the path for resource to be scanned. This will override the directory if both are provided.
          # check: CKV_AZURE_14 # optional: run only a specific check_id. can be comma separated list
          # skip_check: CKV_AWS_2 # optional: skip a specific check_id. can be comma separated list
          # quiet: true # optional: display only failed checks
          # soft_fail: true # optional: do not return an error code if there are failed checks
          framework: terraform # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
          output_format: junitxml # optional: the output format, one of: cli, json, junitxml, github_failed_only, or sarif. Default: sarif
          output_file_path: . # folder and name of results file
          download_external_modules: true # optional: download external terraform modules from public git repositories and terraform registry
          # var_file: ./testdir/gocd.yaml # optional: variable files to load in addition to the default files. Currently only supported for source Terraform and Helm chart scans.
          log_level: DEBUG # optional: set log level. Default WARNING
          # config_file: path/this_file
          # baseline: cloudformation/.checkov.baseline # optional: Path to a generated baseline file. Will only report results not in the baseline.
          # container_user: 1000 # optional: Define what UID and / or what GID to run the container under to prevent permission issues

      - name: Debug Commands
        id: debug_commands
        run: |
          echo "$CHECKOV_RESULTS" > Checkov_Test_Report.xml
          pwd
          ls ..
          pwd
          ls -al
          cd $GITHUB_WORKSPACE
          pwd

      # Publish Checkov test results
      # - name: Publish Checkov Test Results
      #   id: checkov_test_results
      #   uses: mikepenz/action-junit-report@v3.5.2
      #   with:
      #     report_paths: '**/Checkov_Test_Report.xml'

      # - name: Test Reporter
      #   uses: dorny/test-reporter@v1.6.0
      #   with:
      #     name: Checkov Tests
      #     path: './Checkov_Test_Report.xml'
      #     list-tests: 'all'
      #     reporter: java-junit

      - name: Publish Checkov Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.2.0
        with:
          junit_files: "**/*.xml"

      # ALL CODE BELOW HAS BEEN COMMENTED OUT AS TERRAFORM COMMANDS NEED TO BE CONVERTED TO TERRAGRUNT

      - name: Terraform Plan
        id: tf_plan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        # if: github.event_name == 'pull_request' # Disabled for the time being
        run: terraform plan -no-color -out=$GITHUB_WORKSPACE/terraform.json
        continue-on-error: true # Really?

      # Verify Terraform plan file with Checkov
      - name: Checkov GitHub Action
        id: checkov_verify_plan
        uses: bridgecrewio/checkov-action@master
        continue-on-error: true
        with:
          # directory: .
          file: $GITHUB_WORKSPACE/terraform.json # optional: provide the path for resource to be scanned. This will override the directory if both are provided.
          # check: CKV_AZURE_14 # optional: run only a specific check_id. can be comma separated list
          # skip_check: CKV_AWS_2 # optional: skip a specific check_id. can be comma separated list
          # quiet: true # optional: display only failed checks
          # soft_fail: true # optional: do not return an error code if there are failed checks
          framework: terraform # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
          output_format: junitxml # optional: the output format, one of: cli, json, junitxml, github_failed_only, or sarif. Default: sarif
          output_file_path: . # folder and name of results file
          download_external_modules: true # optional: download external terraform modules from public git repositories and terraform registry
          # var_file: ./testdir/gocd.yaml # optional: variable files to load in addition to the default files. Currently only supported for source Terraform and Helm chart scans.
          log_level: DEBUG # optional: set log level. Default WARNING
          # config_file: path/this_file
          # baseline: cloudformation/.checkov.baseline # optional: Path to a generated baseline file. Will only report results not in the baseline.
          # container_user: 1000 # optional: Define what UID and / or what GID to run the container under to prevent permission issues

      - name: Debug Commands 2
        id: debug_commands_2
        run: |
          echo "$CHECKOV_RESULTS"

      # # TODO: Publish Checkov test results for plan file

      # # Insert plan as pull request comments
      # - uses: actions/github-script@v6
      #   # if: github.event_name == 'pull_request' # Disabled for the time being
      #   env:
      #     PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #   # with:
      #   #   github-token: ${{ secrets.GITHUB_TOKEN }} # Should not be needed
      #     script: |
      #       const output = `#### Terraform format and style: \`${{ steps.fmt.outcome }}\`
      #       #### Terraform initialization: \`${{ steps.init.outcome }}\`
      #       #### Terraform validation: \`${{ steps.validate.outcome }}\`
      #       #### Terraform plan: \`${{ steps.plan.outcome }}\`

      #       <details><summary>Show Plan</summary>

      #       \`\`\`\n
      #       ${process.env.PLAN}
      #       \`\`\`

      #       </details>

      #       *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

      #       github.rest.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: output
      #       })

      # - name: Terraform Plan Status
      #   if: steps.plan.outcome == 'failure'
      #   run: exit 1

      # # Upload plan file as build artifact

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: terraform-plan
      #     path: ${{ github.workspace }}/terraform.tfplan